(()=>{
  const SDK='12.16.0';
  const CONFIG_KEY='bydrrm-riverwatch-firebase-config-v1';
  const COLLECTION='riverwatch_readings';
  const AUDIT_COLLECTION='riverwatch_audit';
  let fb=null,auth=null,db=null,user=null,isOperator=false,unsubReadings=null,unsubAudit=null,cloudReady=false;
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const style=document.createElement('style');style.textContent=`
    .rw-cloud-pill{display:inline-flex;align-items:center;gap:7px;border:1px solid #1f3a54;background:#0a1929;color:#c8dceb;padding:8px 11px;border-radius:999px;font-size:11px;font-weight:800;cursor:pointer}.rw-cloud-dot{width:8px;height:8px;border-radius:50%;background:#7f91a4}.rw-cloud-dot.on{background:#2dd4a8}.rw-cloud-dot.warn{background:#ffd166}.rw-cloud-dialog{border:1px solid #2a5879;border-radius:18px;background:#0b1a2a;color:#edf6ff;padding:0;width:min(680px,94vw)}.rw-cloud-dialog::backdrop{background:#000a}.rw-cloud-modal{padding:20px}.rw-cloud-modal h2{margin:0}.rw-cloud-sub{font-size:12px;color:#8ca7bf;line-height:1.55;margin-top:5px}.rw-cloud-status{margin:14px 0;padding:11px;border:1px solid #234b6a;border-radius:11px;background:#0b2238;font-size:11px;line-height:1.55}.rw-cloud-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.rw-cloud-field{display:flex;flex-direction:column;gap:5px}.rw-cloud-field.full{grid-column:1/-1}.rw-cloud-field label{font-size:11px;color:#9db5c9}.rw-cloud-input{background:#071522;border:1px solid #1f3a54;color:#edf6ff;border-radius:10px;padding:10px;width:100%}.rw-cloud-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.rw-cloud-code{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:10px;word-break:break-all;color:#bcd5e6}.rw-cloud-note{font-size:10px;color:#8ca7bf;line-height:1.5;margin-top:10px}@media(max-width:650px){.rw-cloud-grid{grid-template-columns:1fr}.rw-cloud-field.full{grid-column:auto}}
  `;document.head.appendChild(style);

  const toolbar=document.querySelector('.toolbar');const cloudBtn=document.createElement('button');cloudBtn.className='rw-cloud-pill';cloudBtn.id='rwCloudBtn';cloudBtn.innerHTML='<span class="rw-cloud-dot" id="rwCloudDot"></span><span id="rwCloudLabel">Cloud: Local only</span>';if(toolbar)toolbar.appendChild(cloudBtn);
  const dlg=document.createElement('dialog');dlg.className='rw-cloud-dialog';dlg.id='rwCloudDialog';dlg.innerHTML=`<div class="rw-cloud-modal"><h2>☁️ RiverWatch Shared Cloud</h2><div class="rw-cloud-sub">Connect a Firebase project to share verified readings across authorized BYDRRM devices. The Firebase web config identifies the project; write permission is still enforced by Authentication + Firestore Security Rules.</div><div id="rwCloudStatus" class="rw-cloud-status">Local-only mode.</div><div class="rw-cloud-grid"><div class="rw-cloud-field full"><label>Firebase web configuration JSON</label><textarea id="rwCloudConfig" class="rw-cloud-input" rows="8" placeholder='{"apiKey":"...","authDomain":"...","projectId":"...","appId":"..."}'></textarea></div><div class="rw-cloud-field full"><label>Signed-in account / UID</label><div id="rwCloudIdentity" class="rw-cloud-code">Not signed in</div></div></div><div class="rw-cloud-actions"><button class="btn primary" id="rwCloudSave">Save & Connect</button><button class="btn" id="rwCloudSignIn">Sign in with Google</button><button class="btn" id="rwCloudCopyUid">Copy UID</button><button class="btn" id="rwCloudSignOut">Sign out</button><button class="btn danger" id="rwCloudForget">Forget config</button><button class="btn" id="rwCloudClose">Close</button></div><div class="rw-cloud-note">Recommended setup: public read access to <b>riverwatch_readings</b>; only authenticated UIDs present in <b>operators/{uid}</b> may write. Audit records remain operator-only. Field photos stay local in this version and are not uploaded to Firestore.</div></div>`;document.body.appendChild(dlg);

  function config(){try{return window.RIVERWATCH_FIREBASE_CONFIG||JSON.parse(localStorage.getItem(CONFIG_KEY)||'null');}catch{return null;}}
  function setState(kind,label,detail){$('rwCloudDot').className='rw-cloud-dot '+(kind==='on'?'on':kind==='warn'?'warn':'');$('rwCloudLabel').textContent=label;$('rwCloudStatus').innerHTML=detail||label;}
  function sanitizeReading(id,r){return {readingId:r.id||id,stationId:Number(id),level:Number(r.level),status:r.status||'READING_ONLY',time:r.time,source:r.source||'BYDRRM Verified Field Observation',note:r.note||'',updatedAt:new Date().toISOString()};}
  function auditPayload(id,r){const v=r.verification||{};return {readingId:r.id,stationId:Number(id),level:Number(r.level),status:r.status||'READING_ONLY',time:r.time,verifier:v.verifier||'',role:v.role||'',observedSource:v.observedSource||'',evidence:v.evidence||'',photoName:v.photoName||'',verifiedAt:v.verifiedAt||new Date().toISOString(),source:r.source||'',note:r.note||'',uid:user?.uid||'',email:user?.email||'',updatedAt:new Date().toISOString()};}

  async function loadSdk(){if(fb)return fb;const [appMod,authMod,fsMod]=await Promise.all([import(`https://www.gstatic.com/firebasejs/${SDK}/firebase-app.js`),import(`https://www.gstatic.com/firebasejs/${SDK}/firebase-auth.js`),import(`https://www.gstatic.com/firebasejs/${SDK}/firebase-firestore.js`)]);fb={...appMod,...authMod,...fsMod};return fb;}
  async function connect(){const cfg=config();if(!cfg?.apiKey||!cfg?.projectId){setState('off','Cloud: Local only','No Firebase project configured. Local operations remain available.');return false;}try{await loadSdk();const app=fb.getApps().length?fb.getApps()[0]:fb.initializeApp(cfg);auth=fb.getAuth(app);db=fb.getFirestore(app);cloudReady=true;fb.onAuthStateChanged(auth,async u=>{user=u||null;isOperator=false;renderIdentity();if(user){try{const op=await fb.getDoc(fb.doc(db,'operators',user.uid));isOperator=op.exists();}catch{}renderIdentity();}startListeners();});setState('warn','Cloud: Connected','Firebase connected. Sign in with an approved Google account to submit shared verified readings.');startListeners();return true;}catch(e){cloudReady=false;setState('warn','Cloud: Setup needed',`Firebase connection failed: ${esc(e.message||e)}`);return false;}}
  function renderIdentity(){if(!user){$('rwCloudIdentity').textContent='Not signed in';if(cloudReady)setState('warn','Cloud: Read-only','Connected to shared data; sign in as an approved operator to write.');return;}$('rwCloudIdentity').textContent=`${user.email||user.displayName||'Google account'} | UID: ${user.uid} | ${isOperator?'APPROVED OPERATOR':'NOT YET APPROVED'}`;setState(isOperator?'on':'warn',isOperator?'Cloud: Operator online':'Cloud: Approval needed',isOperator?'Realtime shared mode active. Verified readings from this device can sync to all viewers.':`Signed in, but this UID is not listed in operators/${user.uid}. Public shared readings remain viewable.`);}
  function mergeRemoteDocs(snapshot){let changed=false;snapshot.forEach(docSnap=>{const d=docSnap.data();if(!d||!d.stationId||d.level==null||!d.time)return;const id=Number(d.stationId);readings[id]=readings[id]||[];if(readings[id].some(r=>(r.id&&r.id===d.readingId)||(r.time===d.time&&Number(r.level)===Number(d.level)&&r.source===d.source)))return;readings[id].push({id:d.readingId||docSnap.id,level:Number(d.level),status:d.status||'READING_ONLY',time:d.time,source:d.source||'RiverWatch Cloud',note:d.note||'',demo:false,cloud:true});readings[id].sort((a,b)=>new Date(a.time)-new Date(b.time));readings[id]=readings[id].slice(-96);changed=true;});if(changed){try{save();}catch{}window.dispatchEvent(new CustomEvent('riverwatch:cloud-merged'));}}
  function startListeners(){if(!cloudReady||!db)return;if(unsubReadings){unsubReadings();unsubReadings=null;}try{const q=fb.query(fb.collection(db,COLLECTION),fb.orderBy('time','desc'),fb.limit(500));unsubReadings=fb.onSnapshot(q,mergeRemoteDocs,e=>setState('warn','Cloud: Read error',esc(e.message||e)));}catch(e){setState('warn','Cloud: Listener error',esc(e.message||e));}}
  async function uploadVerified(stationId,r){if(!cloudReady||!db||!user||!isOperator||!r?.verification?.verified)return false;const rid=r.id||`${stationId}-${Date.parse(r.time)||Date.now()}-${Math.random().toString(36).slice(2)}`;r.id=rid;await fb.setDoc(fb.doc(db,COLLECTION,rid),sanitizeReading(stationId,r),{merge:true});await fb.setDoc(fb.doc(db,AUDIT_COLLECTION,rid),auditPayload(stationId,r),{merge:true});r.cloudSynced=true;r.cloudSyncedAt=new Date().toISOString();try{save();}catch{}return true;}
  async function syncPending(){if(!isOperator)return;for(const s of STATIONS){for(const r of(readings[s.id]||[])){if(r?.verification?.verified&&!r.cloudSynced){try{await uploadVerified(s.id,r);}catch(e){console.warn('RiverWatch cloud upload failed',e);}}}}}
  window.addEventListener('riverwatch:verified-reading',e=>{const d=e.detail||{};uploadVerified(d.stationId,d.reading).catch(()=>{});});
  window.addEventListener('riverwatch:cloud-merged',()=>{if(typeof window.refreshOps==='function')window.refreshOps();});
  setInterval(syncPending,12000);

  cloudBtn.onclick=()=>{const c=config();$('rwCloudConfig').value=c?JSON.stringify(c,null,2):'';renderIdentity();dlg.showModal();};$('rwCloudClose').onclick=()=>dlg.close();
  $('rwCloudSave').onclick=async()=>{try{const c=JSON.parse($('rwCloudConfig').value);localStorage.setItem(CONFIG_KEY,JSON.stringify(c));await connect();}catch(e){setState('warn','Cloud: Invalid config',`Check the Firebase config JSON: ${esc(e.message||e)}`);}};
  $('rwCloudSignIn').onclick=async()=>{if(!cloudReady&&!(await connect()))return;try{const provider=new fb.GoogleAuthProvider();await fb.signInWithPopup(auth,provider);setTimeout(syncPending,600);}catch(e){setState('warn','Cloud: Sign-in failed',esc(e.message||e));}};
  $('rwCloudSignOut').onclick=async()=>{if(auth)await fb.signOut(auth);};$('rwCloudCopyUid').onclick=async()=>{if(!user)return;try{await navigator.clipboard.writeText(user.uid);$('rwCloudCopyUid').textContent='UID copied';setTimeout(()=>$('rwCloudCopyUid').textContent='Copy UID',1200);}catch{}};
  $('rwCloudForget').onclick=()=>{localStorage.removeItem(CONFIG_KEY);location.reload();};

  connect();
})();